import { useEffect, useMemo, useState } from 'react'
import { ApiOutlined, AppstoreOutlined, CloudServerOutlined, CodeOutlined, LinkOutlined, LockOutlined, LogoutOutlined, PlayCircleOutlined, PlusOutlined, ReloadOutlined, StopOutlined, TeamOutlined, UserOutlined } from '@ant-design/icons'
import { Alert, Button, Card, Col, ConfigProvider, Descriptions, Empty, Flex, Form, Input, Layout, Modal, Row, Select, Space, Statistic, Switch, Table, Tabs, Tag, Typography, message, theme } from 'antd'
import type { TableProps } from 'antd'
import { clearSession, login, logout, request, saveSession, storedSession, type Session, type UserSession } from './auth'

type Component={id:string;name:string;kind:'SERVER'|'WEB'|'TASK'|'DATABASE';sourcePath:string;technology:string}
type Link={name:string;url:string}
type Application={id:string;sortOrder:number;name:string;description:string;category:string;sourceRoot:string;runtime:string;lifecycleEnabled:boolean;status:string;statusDetail:string;links:Link[];components:Component[]}
type Role={code:string;name:string;permissions:string[]}
const statuses:Record<string,{label:string;color:string}>={RUNNING:{label:'运行中',color:'success'},STOPPED:{label:'已停止',color:'default'},UNAVAILABLE:{label:'不可用',color:'error'},DISABLED:{label:'当前平台',color:'processing'},UNKNOWN:{label:'未知',color:'processing'}}
const kindColors:Record<Component['kind'],string>={SERVER:'blue',WEB:'green',TASK:'orange',DATABASE:'purple'}

function LoginPage({onLogin}:{onLogin:(session:Session)=>void}){
  const[busy,setBusy]=useState(false),[error,setError]=useState('')
  const submit=async(values:{username:string;password:string})=>{setBusy(true);setError('');try{const session=await login(values.username,values.password);saveSession(session);onLogin(session)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  return <Layout className="login-shell"><Card className="login-card"><Space direction="vertical" size="large" style={{width:'100%'}}><div><CloudServerOutlined className="login-logo"/><Typography.Title level={2}>Service Platform</Typography.Title><Typography.Text type="secondary">请登录本地服务控制台</Typography.Text></div>{error&&<Alert type="error" showIcon message={error}/>}<Form layout="vertical" onFinish={submit} initialValues={{username:'admin'}}><Form.Item name="username" label="用户名" rules={[{required:true}]}><Input size="large" prefix={<UserOutlined/>}/></Form.Item><Form.Item name="password" label="密码" rules={[{required:true}]}><Input.Password size="large" prefix={<LockOutlined/>}/></Form.Item><Button block size="large" type="primary" htmlType="submit" loading={busy}>登录</Button></Form></Space></Card></Layout>
}

export default function App(){
  const[session,setSession]=useState<Session|undefined>(storedSession()),[apps,setApps]=useState<Application[]>([]),[users,setUsers]=useState<UserSession[]>([]),[roles,setRoles]=useState<Role[]>([])
  const[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[createOpen,setCreateOpen]=useState(false)
  const[msg,holder]=message.useMessage(),[createForm]=Form.useForm()
  const permissions=session?.user.permissions||[],isAdmin=permissions.includes('platform:admin'),canLifecycle=permissions.includes('platform:lifecycle')
  useEffect(()=>{const expired=()=>setSession(undefined);window.addEventListener('platform-auth-expired',expired);return()=>window.removeEventListener('platform-auth-expired',expired)},[])
  const loadApps=async(quiet=false)=>{if(!quiet)setLoading(true);try{setApps(await request('/api/applications'));setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{if(!quiet)setLoading(false)}}
  const loadUsers=async()=>{if(!isAdmin)return;try{const[u,r]=await Promise.all([request<UserSession[]>('/api/admin/users'),request<Role[]>('/api/admin/roles')]);setUsers(u);setRoles(r)}catch(e){msg.error(e instanceof Error?e.message:String(e))}}
  useEffect(()=>{if(!session)return;loadApps();loadUsers();const timer=setInterval(()=>loadApps(true),10000);return()=>clearInterval(timer)},[session?.accessToken])
  const totals=useMemo(()=>({components:apps.reduce((sum,app)=>sum+app.components.length,0),running:apps.filter(app=>app.status==='RUNNING').length}),[apps])
  const lifecycle=async(app:Application,operation:'start'|'stop')=>{setBusy(`${app.id}:${operation}`);try{await request(`/api/applications/${app.id}/${operation}`,{method:'POST'});msg.success(`${app.name}${operation==='start'?'启动':'停止'}完成`);await loadApps(true)}catch(e){msg.error(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  const signOut=async()=>{try{await logout()}catch{}finally{clearSession();setSession(undefined)}}
  const createUser=async()=>{const values=await createForm.validateFields();try{await request('/api/admin/users',{method:'POST',body:JSON.stringify(values)});msg.success('用户已创建');setCreateOpen(false);createForm.resetFields();loadUsers()}catch(e){msg.error(e instanceof Error?e.message:String(e))}}
  const updateRoles=async(user:UserSession,value:string[])=>{try{await request(`/api/admin/users/${user.id}/roles`,{method:'PUT',body:JSON.stringify({roles:value})});msg.success('角色已更新');loadUsers()}catch(e){msg.error(e instanceof Error?e.message:String(e))}}
  const updateEnabled=async(user:UserSession,enabled:boolean)=>{try{await request(`/api/admin/users/${user.id}/enabled`,{method:'PUT',body:JSON.stringify({enabled})});msg.success('状态已更新');loadUsers()}catch(e){msg.error(e instanceof Error?e.message:String(e))}}
  const resetPassword=(user:UserSession)=>{let password='';Modal.confirm({title:`重置 ${user.username} 的密码`,content:<Input.Password placeholder="至少 8 位" onChange={e=>password=e.target.value}/>,onOk:async()=>{if(password.length<8)throw new Error('密码至少 8 位');await request(`/api/admin/users/${user.id}/password`,{method:'PUT',body:JSON.stringify({password})});msg.success('密码已重置')}})}
  if(!session)return <ConfigProvider theme={{token:{colorPrimary:'#315bd8',borderRadius:10}}}><LoginPage onLogin={setSession}/></ConfigProvider>

  const appView=<>{error&&<Alert showIcon type="error" message="平台连接异常" description={error} className="error-alert"/>}<Row gutter={[16,16]} className="metrics"><Col xs={24} sm={8}><Card><Statistic title="已登记应用" value={apps.length} prefix={<AppstoreOutlined/>}/></Card></Col><Col xs={24} sm={8}><Card><Statistic title="代码组件" value={totals.components} prefix={<CodeOutlined/>}/></Card></Col><Col xs={24} sm={8}><Card><Statistic title="运行中" value={totals.running} prefix={<ApiOutlined/>}/></Card></Col></Row>{apps.length===0&&!loading?<Card><Empty description="尚未登记应用"/></Card>:<Row gutter={[16,16]}>{apps.map(app=>{const meta=statuses[app.status]||statuses.UNKNOWN;return <Col xs={24} xl={12} key={app.id}><Card loading={loading&&apps.length===0} className="app-card"><Flex justify="space-between" align="flex-start"><div><Tag color="geekblue">{app.category}</Tag><Typography.Title level={3}>{app.name}</Typography.Title></div><Tag color={meta.color} style={{borderRadius:999,padding:'2px 10px',margin:0}}>{meta.label}</Tag></Flex><Typography.Paragraph type="secondary">{app.description}</Typography.Paragraph><Descriptions size="small" column={1}><Descriptions.Item label="运行模式">{app.runtime}</Descriptions.Item><Descriptions.Item label="源码目录"><Typography.Text code copyable>{app.sourceRoot}</Typography.Text></Descriptions.Item></Descriptions><div className="component-list">{app.components.map(component=><div className="component" key={component.id}><Tag color={kindColors[component.kind]}>{component.kind}</Tag><div><Typography.Text strong>{component.name}</Typography.Text><Typography.Text type="secondary">{component.technology} · {component.sourcePath}</Typography.Text></div></div>)}</div><Typography.Text type="secondary">{app.statusDetail}</Typography.Text><Flex wrap gap={8} className="actions"><Button type="primary" icon={<PlayCircleOutlined/>} disabled={!app.lifecycleEnabled||!canLifecycle} loading={busy===`${app.id}:start`} onClick={()=>lifecycle(app,'start')}>启动</Button><Button danger icon={<StopOutlined/>} disabled={!app.lifecycleEnabled||!canLifecycle} loading={busy===`${app.id}:stop`} onClick={()=>lifecycle(app,'stop')}>停止</Button>{app.links.map(link=><Button key={link.url} href={link.url} target="_blank" icon={<LinkOutlined/>}>{link.name}</Button>)}</Flex></Card></Col>})}</Row>}</>
  const userColumns:TableProps<UserSession>['columns']=[{title:'用户',render:(_,u)=><><Typography.Text strong>{u.displayName}</Typography.Text><br/><Typography.Text type="secondary">{u.username}</Typography.Text></>},{title:'角色',render:(_,u)=><Select mode="multiple" style={{minWidth:220}} value={u.roles} options={roles.map(r=>({label:r.name,value:r.code}))} onChange={v=>updateRoles(u,v)}/>},{title:'权限',dataIndex:'permissions',responsive:['lg'],render:v=><Space wrap>{v.map((p:string)=><Tag key={p}>{p}</Tag>)}</Space>},{title:'启用',dataIndex:'enabled',width:80,render:(v,u)=><Switch checked={v} disabled={u.id===session.user.id} onChange={checked=>updateEnabled(u,checked)}/>},{title:'操作',width:100,render:(_,u)=><Button onClick={()=>resetPassword(u)}>重置密码</Button>}]
  const userView=<Card title="用户与权限" extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setCreateOpen(true)}>新增用户</Button>}><Table rowKey="id" columns={userColumns} dataSource={users}/></Card>
  const tabs=[{key:'apps',label:<span><AppstoreOutlined/>应用目录</span>,children:appView},...(isAdmin?[{key:'users',label:<span><TeamOutlined/>用户权限</span>,children:userView}]:[])]
  return <ConfigProvider theme={{algorithm:theme.defaultAlgorithm,token:{colorPrimary:'#315bd8',borderRadius:10,colorBgLayout:'#f5f7fb'}}}>{holder}<Layout className="page-shell"><Layout.Header className="topbar"><Flex className="topbar-brand" align="center" gap={12}><div className="brand-icon"><CloudServerOutlined/></div><div className="brand-copy"><Typography.Text strong className="brand-title">Service Platform</Typography.Text><Typography.Text type="secondary" className="brand-meta">{session.user.displayName} · {session.user.roles.join(' / ')}</Typography.Text></div></Flex><Space size={4} className="topbar-actions"><Button type="text" className="toolbar-button" icon={<ReloadOutlined/>} loading={loading} onClick={()=>{loadApps();loadUsers()}}>刷新</Button><Button type="text" className="toolbar-button toolbar-button-danger" icon={<LogoutOutlined/>} onClick={signOut}>退出</Button></Space></Layout.Header><Layout.Content className="content"><Tabs items={tabs}/></Layout.Content><Modal title="新增用户" open={createOpen} onOk={createUser} onCancel={()=>setCreateOpen(false)}><Form form={createForm} layout="vertical"><Form.Item name="username" label="用户名" rules={[{required:true},{pattern:/^[A-Za-z0-9._-]{3,100}$/}]}><Input/></Form.Item><Form.Item name="displayName" label="显示名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="password" label="初始密码" rules={[{required:true},{min:8}]}><Input.Password/></Form.Item><Form.Item name="roles" label="角色" initialValue={['VIEWER']}><Select mode="multiple" options={roles.map(r=>({label:r.name,value:r.code}))}/></Form.Item></Form></Modal></Layout></ConfigProvider>
}
