FROM node:22-alpine AS builder
WORKDIR /source
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /source/dist /usr/share/nginx/html
EXPOSE 80
