server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  location /api/ {
    proxy_pass http://platform-server:9090;
    proxy_read_timeout 900s;
  }
  location / { try_files $uri $uri/ /index.html; }
}
