import {useEffect,useMemo,useState} from 'react'
import {DeleteOutlined,EyeOutlined,HistoryOutlined,LockOutlined,LogoutOutlined,PlayCircleOutlined,PlusOutlined,ReloadOutlined,SafetyCertificateOutlined,SettingOutlined,UploadOutlined,UserOutlined} from '@ant-design/icons'
import {Alert,Button,Card,Checkbox,Col,ConfigProvider,Descriptions,Divider,Drawer,Flex,Form,Input,Layout,Modal,Row,Select,Space,Statistic,Table,Tabs,Tag,Tooltip,Typography,Upload,message} from 'antd'
import type{TableProps}from'antd'
import{api,type Execution,type ExecutionLog,type InputField,type Merchant,type MerchantConfigurationField,type Task,type TaskTemplate,type WorkflowTemplate}from'./api'
import{clearSession,login,logout,me,saveSession,storedSession,type Session,type UserSession}from'./auth'

const statusColor:Record<string,string>={QUEUED:'processing',RUNNING:'blue',WAITING:'orange',SUCCEEDED:'success',FAILED:'error',CANCELLED:'default'}
type JsonEntry={key:string;value:string}
type JsonShape='OBJECT'|'ARRAY'
const findOutputValue=(value:unknown,key:string,depth=0):string|undefined=>{if(value==null||depth>6)return undefined;if(typeof value==='string'){const text=value.trim();if(text.startsWith('{')||text.startsWith('[')){try{return findOutputValue(JSON.parse(text),key,depth+1)}catch{return undefined}}return undefined}if(typeof value==='object'){const record=value as Record<string,unknown>;const direct=record[key];if(direct!=null&&String(direct).trim())return String(direct);for(const nested of Object.values(record)){const found=findOutputValue(nested,key,depth+1);if(found)return found}}return undefined}

const jsonValueText=(value:unknown)=>typeof value==='string'?value:JSON.stringify(value)
const jsonTextValue=(value:string):unknown=>{const text=value.trim();if(!text)return '';try{return JSON.parse(text)}catch{return value}}
const jsonEntries=(value:unknown):JsonEntry[]=>value&&typeof value==='object'&&!Array.isArray(value)?Object.entries(value).map(([key,item])=>({key,value:jsonValueText(item)})):[]
const parseStructuredJson=(value:string|undefined,shape:JsonShape):JsonEntry[][]=>{if(!value)return shape==='OBJECT'?[[]]:[];try{const parsed=JSON.parse(value);if(shape==='OBJECT'&&!Array.isArray(parsed)&&parsed&&typeof parsed==='object')return[jsonEntries(parsed)];if(shape==='ARRAY'&&Array.isArray(parsed))return parsed.filter(item=>item&&typeof item==='object'&&!Array.isArray(item)).map(jsonEntries)}catch{}return shape==='OBJECT'?[[]]:[]}
const serializeStructuredJson=(objects:JsonEntry[][],shape:JsonShape):string=>{const values=objects.map(entries=>Object.fromEntries(entries.filter(entry=>entry.key.trim()).map(entry=>[entry.key.trim(),jsonTextValue(entry.value)])));if(shape==='OBJECT')return values[0]&&Object.keys(values[0]).length?JSON.stringify(values[0]):'';return values.length?JSON.stringify(values):''}

function StructuredJsonEditor({value,onChange,shape,disabled=false}:{value?:string;onChange?:(value:string)=>void;shape:JsonShape;disabled?:boolean}){
  const[objects,setObjects]=useState<JsonEntry[][]>(()=>parseStructuredJson(value,shape))
  useEffect(()=>{const current=serializeStructuredJson(objects,shape);if((value||'')!==current)setObjects(parseStructuredJson(value,shape))},[value,shape])
  const commit=(next:JsonEntry[][])=>{setObjects(next);onChange?.(serializeStructuredJson(next,shape))}
  const updateEntry=(objectIndex:number,entryIndex:number,key:'key'|'value',nextValue:string)=>{const next=objects.map(entries=>entries.map(entry=>({...entry})));next[objectIndex][entryIndex][key]=nextValue;commit(next)}
  const addEntry=(objectIndex:number)=>{const next=objects.map(entries=>entries.map(entry=>({...entry})));next[objectIndex]=[...(next[objectIndex]||[]),{key:'',value:''}];commit(next)}
  const removeEntry=(objectIndex:number,entryIndex:number)=>commit(objects.map((entries,index)=>index===objectIndex?entries.filter((_,itemIndex)=>itemIndex!==entryIndex):entries))
  const addObject=()=>commit([...objects,[{key:'',value:''}]])
  const removeObject=(objectIndex:number)=>commit(objects.filter((_,index)=>index!==objectIndex))
  return <div className="structured-json-editor">{objects.map((entries,objectIndex)=><Card key={objectIndex} size="small" className="json-object-card" title={shape==='ARRAY'?`对象 ${objectIndex+1}`:'JSON Object'} extra={shape==='ARRAY'&&!disabled?<Button danger type="text" size="small" icon={<DeleteOutlined/>} onClick={()=>removeObject(objectIndex)}>删除对象</Button>:undefined}>{entries.map((entry,entryIndex)=><Flex key={entryIndex} gap={8} align="flex-start" className="json-entry-row"><Input disabled={disabled} value={entry.key} placeholder="字段名" onChange={event=>updateEntry(objectIndex,entryIndex,'key',event.target.value)}/><Input disabled={disabled} value={entry.value} placeholder='值（支持字符串、数字、布尔值或 JSON）' onChange={event=>updateEntry(objectIndex,entryIndex,'value',event.target.value)}/>{!disabled&&<Button danger type="text" icon={<DeleteOutlined/>} aria-label="删除字段" onClick={()=>removeEntry(objectIndex,entryIndex)}/>}</Flex>)}{!disabled&&<Button type="dashed" size="small" icon={<PlusOutlined/>} onClick={()=>addEntry(objectIndex)}>新增字段</Button>}</Card>)}{shape==='ARRAY'&&!disabled&&<Button block type="dashed" icon={<PlusOutlined/>} onClick={addObject}>新增 JSON Object</Button>}</div>
}

function ImageFilePicker({value,onChange,disabled=false}:{value?:string;onChange?:(value:string)=>void;disabled?:boolean}){
  const[uploading,setUploading]=useState(false)
  if(disabled)return <Input value={value} placeholder="运行时选择本地图片" disabled/>
  return <Space direction="vertical" style={{width:'100%'}}><Upload accept=".jpg,.jpeg,.png,image/jpeg,image/png" maxCount={1} showUploadList={false} beforeUpload={async file=>{setUploading(true);try{const result=await api.uploadImage(file);onChange?.(result.path);message.success(`${result.name} 已选择`)}catch(error){message.error(error instanceof Error?error.message:String(error))}finally{setUploading(false)}return false}}><Button icon={<UploadOutlined/>} loading={uploading}>选择本地图片</Button></Upload>{value&&<Typography.Text type="secondary">已上传：{value.split(/[\\/]/).pop()}</Typography.Text>}</Space>
}

function LoginPage({done}:{done:(session:Session)=>void}){const[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(v:{username:string;password:string})=>{setBusy(true);setError('');try{const s=await login(v.username,v.password);saveSession(s);done(s)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};return <Layout className="login-shell"><Card className="login-card"><Typography.Title level={2}>Task Center</Typography.Title><Typography.Text type="secondary">使用平台账号登录</Typography.Text>{error&&<Alert style={{margin:'20px 0'}} type="error" showIcon message={error}/>}<Form layout="vertical" onFinish={submit} style={{marginTop:24}}><Form.Item name="username" label="用户名" rules={[{required:true}]}><Input prefix={<UserOutlined/>}/></Form.Item><Form.Item name="password" label="密码" rules={[{required:true}]}><Input.Password prefix={<LockOutlined/>}/></Form.Item><Button block type="primary" htmlType="submit" loading={busy}>登录</Button></Form></Card></Layout>}

export default function App(){
  const[user,setUser]=useState<UserSession|undefined>(storedSession()?.user),[authLoading,setAuthLoading]=useState(true)
  const[tasks,setTasks]=useState<Task[]>([]),[templates,setTemplates]=useState<TaskTemplate[]>([]),[workflows,setWorkflows]=useState<WorkflowTemplate[]>([]),[merchants,setMerchants]=useState<Merchant[]>([]),[executions,setExecutions]=useState<Execution[]>([])
  const[configurationFields,setConfigurationFields]=useState<MerchantConfigurationField[]>([])
  const[loading,setLoading]=useState(true),[runTask,setRunTask]=useState<Task>(),[confirmed,setConfirmed]=useState(false),[logs,setLogs]=useState<ExecutionLog[]>([]),[logOpen,setLogOpen]=useState(false)
  const[toggleTarget,setToggleTarget]=useState<{task:Task;enabled:boolean}>(),[merchantFilter,setMerchantFilter]=useState<string>()
  const[taskCreateOpen,setTaskCreateOpen]=useState(false),[merchantCreateOpen,setMerchantCreateOpen]=useState(false),[configMerchant,setConfigMerchant]=useState<Merchant>()
  const[selectedTemplate,setSelectedTemplate]=useState<TaskTemplate>(),[selectedWorkflow,setSelectedWorkflow]=useState<WorkflowTemplate>()
  const[selectedExecution,setSelectedExecution]=useState<Execution>()
  const[msg,holder]=message.useMessage(),[runForm]=Form.useForm(),[taskForm]=Form.useForm(),[merchantForm]=Form.useForm(),[configForm]=Form.useForm()
  const canRead=user?.permissions.includes('task:read'),canManage=user?.permissions.includes('task:manage'),canExecute=user?.permissions.includes('task:execute')
  useEffect(()=>{const expired=()=>setUser(undefined);window.addEventListener('platform-auth-expired',expired);me().then(setUser).catch(()=>{}).finally(()=>setAuthLoading(false));return()=>window.removeEventListener('platform-auth-expired',expired)},[])
  const load=async(quiet=false)=>{if(!canRead)return;if(!quiet)setLoading(true);try{const[t,e,m,p,w,c]=await Promise.all([api.tasks(),api.executions(),api.merchants(),api.templates(),api.workflows(),api.merchantConfigurationFields()]);setTasks(t);setExecutions(e);setMerchants(m);setTemplates(p);setWorkflows(w);setConfigurationFields(c)}catch(error){msg.error(error instanceof Error?error.message:String(error))}finally{if(!quiet)setLoading(false)}}
  useEffect(()=>{if(!user)return;load();const timer=setInterval(()=>load(true),5000);return()=>clearInterval(timer)},[user?.username])
  const running=useMemo(()=>executions.filter(e=>['QUEUED','RUNNING'].includes(e.status)).length,[executions]),visibleTasks=useMemo(()=>merchantFilter?tasks.filter(task=>task.merchantId===merchantFilter):tasks,[tasks,merchantFilter])
  const toggle=async()=>{if(!toggleTarget)return;try{await api.enable(toggleTarget.task.id,toggleTarget.enabled);msg.success(`${toggleTarget.task.displayName} 已${toggleTarget.enabled?'启用':'禁用'}`);setToggleTarget(undefined);await load(true)}catch(e){msg.error(e instanceof Error?e.message:String(e))}}
  const openRun=(task:Task)=>{setRunTask(task);setConfirmed(false);runForm.setFieldsValue({inputs:Object.fromEntries(task.inputFields.filter(f=>f.defaultValue).map(f=>[f.key,f.defaultValue]))})}
  const submitRun=async()=>{if(!runTask)return;try{const values=await runForm.validateFields();const inputs=values.inputs||{};if(runTask.inputFields.some(field=>field.key==='file_path')&&Boolean(inputs.file_path)===Boolean(inputs.file_url))throw new Error('本地图片和图片 URL 必须且只能选择一种');await api.run(runTask.id,[],inputs,confirmed);msg.success('任务已提交');setRunTask(undefined);setConfirmed(false);runForm.resetFields();load(true)}catch(e){if(e instanceof Error)msg.error(e.message)}}
  const createTask=async()=>{try{const value=await taskForm.validateFields();const[templateType,templateId]=String(value.templateSelection).split(':',2);const payload={id:value.id,displayName:value.displayName,description:value.description,merchantId:value.merchantId,...templateType==='workflow'?{workflowTemplateId:templateId}:{templateTaskId:templateId}};await api.createTask(payload);msg.success('任务已创建，默认处于禁用状态');setTaskCreateOpen(false);taskForm.resetFields();load(true)}catch(e){if(e instanceof Error)msg.error(e.message)}}
  const createMerchant=async()=>{try{const value=await merchantForm.validateFields();await api.createMerchant({...value,configuration:value.configuration||{}});msg.success('商户配置已注册');setMerchantCreateOpen(false);merchantForm.resetFields();load(true)}catch(e){if(e instanceof Error)msg.error(e.message)}}
  const openConfiguration=async(merchant:Merchant)=>{try{const value=await api.merchantConfiguration(merchant.id);setConfigMerchant(merchant);configForm.setFieldsValue({configuration:value.configuration})}catch(e){msg.error(e instanceof Error?e.message:String(e))}}
  const saveConfiguration=async()=>{if(!configMerchant)return;try{const value=await configForm.validateFields();await api.updateMerchantConfiguration(configMerchant.id,value.configuration||{});msg.success('商户配置已更新');setConfigMerchant(undefined);configForm.resetFields();load(true)}catch(e){if(e instanceof Error)msg.error(e.message)}}
  const showLogs=async(execution:Execution)=>{try{setLogs(await api.logs(execution.id));setLogOpen(true)}catch(e){msg.error(e instanceof Error?e.message:String(e))}},signOut=async()=>{try{await logout()}catch{}finally{clearSession();setUser(undefined)}}
  const queryNow=async(execution:Execution)=>{try{await api.queryNow(execution.id);msg.success('已触发立即查询');load(true)}catch(e){msg.error(e instanceof Error?e.message:String(e))}}
  if(authLoading)return <Layout className="login-shell"><Typography.Text>正在检查登录状态…</Typography.Text></Layout>
  if(!user)return <ConfigProvider theme={{token:{colorPrimary:'#315bd8'}}}><LoginPage done={s=>setUser(s.user)}/></ConfigProvider>

  const taskColumns:TableProps<Task>['columns']=[
    {title:'任务',dataIndex:'displayName',render:(value,task)=><div><Typography.Text strong>{value}</Typography.Text><br/><Typography.Text type="secondary">{task.id}</Typography.Text></div>},
    {title:'商户',dataIndex:'merchantName',width:140,render:(value,task)=>value?<Tag color="blue">{value}</Tag>:<Tag>{task.category}</Tag>},
    {title:'执行模板',responsive:['lg'],render:(_,task)=><Typography.Text type="secondary">{task.workflowName||templates.find(item=>item.id===task.templateTaskId)?.displayName||task.templateTaskId}</Typography.Text>},
    {title:'页面输入',responsive:['md'],render:(_,task)=><Space wrap>{task.inputFields.map(f=><Tag color={f.required?'red':'default'} key={f.key}>{f.label} · {f.required?'必填':'选填'}</Tag>)}</Space>},
    {title:'状态',dataIndex:'enabled',width:90,render:enabled=><Tag color={enabled?'success':'default'}>{enabled?'已启用':'未启用'}</Tag>},
    {title:'操作',width:210,render:(_,task)=><Space><Tooltip title={!canManage?'当前账号没有 task:manage 权限':''}><Button disabled={!canManage} danger={task.enabled} onClick={()=>setToggleTarget({task,enabled:!task.enabled})}>{task.enabled?'禁用':'启用'}</Button></Tooltip><Button type="primary" icon={<PlayCircleOutlined/>} disabled={!task.enabled||running>0||!canExecute} onClick={()=>openRun(task)}>填写并执行</Button></Space>}
  ]
  const merchantColumns:TableProps<Merchant>['columns']=[{title:'商户',render:(_,merchant)=><div><Typography.Text strong>{merchant.name}</Typography.Text><br/><Typography.Text type="secondary">{merchant.code.toLowerCase()}</Typography.Text></div>},{title:'说明',dataIndex:'description'},{title:'配置项',dataIndex:'configurationKeys',render:(keys:string[])=><Space wrap>{keys.length?keys.map(key=><Tag key={key}>{key}</Tag>):<Typography.Text type="secondary">暂无</Typography.Text>}</Space>},{title:'操作',width:110,render:(_,merchant)=><Button icon={<SettingOutlined/>} disabled={!canManage} onClick={()=>openConfiguration(merchant)}>配置</Button>}]
  const templateColumns:TableProps<TaskTemplate>['columns']=[{title:'模板',width:220,render:(_,template)=><div><Button type="link" className="template-name-link" onClick={()=>setSelectedTemplate(template)}>{template.displayName}</Button><br/><Typography.Text type="secondary">{template.id}</Typography.Text></div>},{title:'分类',dataIndex:'category',width:120,render:value=><Tag>{value}</Tag>},{title:'模板字段',dataIndex:'inputFields',render:(fields:InputField[])=><Space wrap>{fields.map(field=><Tag color={field.required?'red':'default'} key={field.key}>{field.label} · {field.required?'必填':'选填'}</Tag>)}</Space>},{title:'操作',width:110,render:(_,template)=><Button icon={<EyeOutlined/>} onClick={()=>setSelectedTemplate(template)}>查看详情</Button>}]
  const workflowColumns:TableProps<WorkflowTemplate>['columns']=[{title:'流程模板',width:260,render:(_,workflow)=><div><Button type="link" className="template-name-link" onClick={()=>setSelectedWorkflow(workflow)}>{workflow.displayName}</Button><br/><Typography.Text type="secondary">{workflow.id} · v{workflow.version}</Typography.Text></div>},{title:'步骤',render:(_,workflow)=><Space wrap>{workflow.steps.map(step=><Tag color={step.polling?'orange':step.optional?'default':'blue'} key={step.key}>{step.order+1}. {step.templateName}{step.optional?'（可选）':''}{step.polling?'（轮询）':''}</Tag>)}</Space>},{title:'操作',width:110,render:(_,workflow)=><Button icon={<EyeOutlined/>} onClick={()=>setSelectedWorkflow(workflow)}>查看详情</Button>}]
  const executionColumns:TableProps<Execution>['columns']=[{title:'任务',dataIndex:'taskName'},{title:'状态',dataIndex:'status',width:110,render:v=><Tag color={statusColor[v]}>{v}</Tag>},{title:'执行步骤',responsive:['md'],render:(_,execution)=><Space wrap>{execution.steps?.map(step=><Tag color={statusColor[step.status]} key={step.id}>{step.stepKey} · {step.status}{step.attemptCount>1?` ×${step.attemptCount}`:''}</Tag>)||'-'}</Space>},{title:'下次查询',dataIndex:'nextRunAt',responsive:['lg'],render:v=>v?new Date(v).toLocaleString():'-'},{title:'申请时间',dataIndex:'requestedAt',width:180,render:v=>new Date(v).toLocaleString()},{title:'结果',responsive:['lg'],render:(_,execution)=>{const fileId=findOutputValue(execution.outputs,'file_id')||findOutputValue(execution.steps,'file_id');return execution.errorMessage?<Typography.Text type="danger">{execution.errorMessage}</Typography.Text>:fileId?<Typography.Text copyable={{text:fileId}}><Typography.Text strong>file_id：</Typography.Text>{fileId}</Typography.Text>:Object.keys(execution.outputs||{}).length||execution.steps?.some(step=>Object.keys(step.outputs||{}).length)?<Typography.Text type="success">已有返回结果</Typography.Text>:'-'}},{title:'操作',width:240,render:(_,execution)=><Space>{execution.status==='WAITING'&&<Button type="primary" disabled={!canExecute} onClick={()=>queryNow(execution)}>立即查询</Button>}<Button onClick={()=>setSelectedExecution(execution)}>结果</Button><Button onClick={()=>showLogs(execution)}>日志</Button></Space>}]
  const renderField=(field:InputField,preview=false)=>{
    const jsonShape=field.type==='JSON_OBJECT'?'OBJECT':field.type==='JSON_ARRAY'?'ARRAY':undefined
    const rules=[...(field.required?[{required:true,message:`请填写${field.label}`}]:[]),...(jsonShape?[{validator:(_:unknown,value?:string)=>{if(!value)return Promise.resolve();try{const parsed=JSON.parse(value);const valid=jsonShape==='OBJECT'?parsed&&typeof parsed==='object'&&!Array.isArray(parsed):Array.isArray(parsed)&&parsed.every(item=>item&&typeof item==='object'&&!Array.isArray(item));return valid?Promise.resolve():Promise.reject(new Error(jsonShape==='OBJECT'?'请输入 JSON Object':'请输入由 JSON Object 组成的 Array'))}catch{return Promise.reject(new Error('JSON 格式不正确'))}}}]:[])]
    const common={placeholder:field.placeholder}
    const control=jsonShape?<StructuredJsonEditor shape={jsonShape} disabled={preview}/>:field.type==='IMAGE_FILE'?<ImageFilePicker disabled={preview}/>:field.type==='TEXTAREA'?<Input.TextArea rows={4}{...common}/>:field.type==='PASSWORD'?<Input.Password {...common}/>:field.type==='SELECT'?<Select showSearch optionFilterProp="label" options={field.options}/>:<Input type={field.type==='URL'?'url':undefined}{...common}/>
    const label=<Space size={6}>{field.label}<Tag color={field.required?'red':'default'}>{field.required?'必填':'选填'}</Tag></Space>
    return <Form.Item key={field.key} name={['inputs',field.key]} label={label} rules={rules} extra={field.description}>{control}</Form.Item>
  }
  const tabItems=[
    {key:'tasks',label:'任务列表',children:<><Flex justify="space-between" gap={12} wrap style={{marginBottom:16}}><Select allowClear placeholder="全部商户" style={{minWidth:220}} value={merchantFilter} onChange={setMerchantFilter} options={merchants.map(item=>({label:`${item.name} (${item.code.toLowerCase()})`,value:item.id}))}/><Button type="primary" icon={<PlusOutlined/>} disabled={!canManage} onClick={()=>setTaskCreateOpen(true)}>新建任务</Button></Flex><Table rowKey="id" loading={loading} columns={taskColumns} dataSource={visibleTasks} pagination={{pageSize:10}}/></>},
    {key:'merchants',label:'商户配置',children:<><Flex justify="flex-end" style={{marginBottom:16}}><Button type="primary" icon={<PlusOutlined/>} disabled={!canManage} onClick={()=>{merchantForm.setFieldsValue({configuration:{}});setMerchantCreateOpen(true)}}>注册商户</Button></Flex><Table rowKey="id" columns={merchantColumns} dataSource={merchants} pagination={{pageSize:10}}/></>},
    {key:'workflows',label:'流程模板',children:<Table rowKey="id" columns={workflowColumns} dataSource={workflows} pagination={{pageSize:10}}/>},
    {key:'templates',label:'任务模板',children:<Table rowKey="id" columns={templateColumns} dataSource={templates} pagination={{pageSize:10}}/>},
    {key:'history',label:'执行历史',children:<Table rowKey="id" loading={loading} columns={executionColumns} dataSource={executions} pagination={{pageSize:10}}/>}
  ]
  return <ConfigProvider theme={{token:{colorPrimary:'#315bd8',borderRadius:10,colorBgLayout:'#f5f7fb'}}}>{holder}<Layout className="shell"><Layout.Header className="task-topbar"><Flex className="task-brand" align="center" gap={12}><div className="task-brand-icon"><SafetyCertificateOutlined/></div><div className="task-brand-copy"><Typography.Text strong className="task-brand-title">Task Center</Typography.Text><Typography.Text type="secondary" className="task-brand-meta">{user.displayName}</Typography.Text></div></Flex><Space size={4} className="task-topbar-actions"><Button type="text" className="task-toolbar-button" icon={<ReloadOutlined/>} loading={loading} onClick={()=>load()}>刷新</Button><Button type="text" className="task-toolbar-button task-toolbar-button-danger" icon={<LogoutOutlined/>} onClick={signOut}>退出</Button></Space></Layout.Header><Layout.Content>{!canManage&&<Alert showIcon type="warning" message="当前登录令牌没有任务管理权限" description="请退出后重新登录，以获取最新权限。"/>}<Row gutter={[16,16]} className="metrics"><Col xs={24} sm={8}><Card><Statistic title="登记任务" value={tasks.length} prefix={<SafetyCertificateOutlined/>}/></Card></Col><Col xs={24} sm={8}><Card><Statistic title="已启用" value={tasks.filter(t=>t.enabled).length}/></Card></Col><Col xs={24} sm={8}><Card><Statistic title="执行中" value={running} prefix={<HistoryOutlined/>}/></Card></Col></Row><Card><Tabs items={tabItems}/></Card>
  <Modal title={toggleTarget?.enabled?'确认启用任务':'确认禁用任务'} open={!!toggleTarget} okText={toggleTarget?.enabled?'确认启用':'确认禁用'} okButtonProps={{danger:!toggleTarget?.enabled}} onOk={toggle} onCancel={()=>setToggleTarget(undefined)}><Alert showIcon type={toggleTarget?.enabled?'warning':'info'} message={toggleTarget?.task.displayName} description={toggleTarget?.enabled?'启用后可提交真实业务执行，每次执行仍需单独确认。':'禁用后不能通过页面或 API 发起执行。'}/></Modal>
  <Modal width={680} title={`填写并执行 ${runTask?.displayName||''}`} open={!!runTask} okText="确认并执行任务" cancelText="取消" okButtonProps={{danger:true,disabled:!confirmed,size:'large'}} cancelButtonProps={{size:'large'}} onOk={submitRun} onCancel={()=>{setRunTask(undefined);setConfirmed(false);runForm.resetFields()}}><Descriptions column={1} size="small"><Descriptions.Item label="商户">{runTask?.merchantName||'-'}</Descriptions.Item><Descriptions.Item label={runTask?.workflowTemplateId?'流程模板':'任务模板'}>{runTask?.workflowName||templates.find(item=>item.id===runTask?.templateTaskId)?.displayName||runTask?.templateTaskId}</Descriptions.Item></Descriptions>{runTask?.workflowTemplateId&&<Alert type="info" showIcon style={{marginTop:12}} message="流程会持久化每个步骤；申请单处理中将按模板间隔轮询，也可在执行历史中立即查询。"/>}<Form form={runForm} layout="vertical" style={{marginTop:16}}>{runTask?.inputFields.map(field=>renderField(field))}</Form><Alert type={confirmed?'success':'warning'} showIcon style={{marginTop:20}} message={<Checkbox checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}><Typography.Text strong>我已核对以上信息，并确认执行真实业务操作</Typography.Text></Checkbox>} description="请再次确认商户、文件和业务参数无误。勾选后才能执行。"/></Modal>
  <Modal title="新建任务" open={taskCreateOpen} onOk={createTask} onCancel={()=>{setTaskCreateOpen(false);taskForm.resetFields()}}><Form form={taskForm} layout="vertical"><Form.Item name="id" label="任务 ID" rules={[{required:true},{pattern:/^[a-z0-9][a-z0-9-]{2,119}$/,message:'使用小写字母、数字和连字符'}]}><Input placeholder="merchant-template-purpose"/></Form.Item><Form.Item name="displayName" label="任务名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="merchantId" label="商户" rules={[{required:true}]}><Select options={merchants.map(item=>({label:`${item.name} (${item.code.toLowerCase()})`,value:item.id}))}/></Form.Item><Form.Item name="templateSelection" label="执行模板" rules={[{required:true}]} extra="组合业务优先选择流程模板；任务模板保留用于单动作和旧任务。"><Select showSearch optionFilterProp="label" options={[{label:'流程模板',options:workflows.map(item=>({label:`${item.displayName} (${item.category})`,value:`workflow:${item.id}`}))},{label:'单动作任务模板',options:templates.map(item=>({label:`${item.displayName} (${item.category})`,value:`task:${item.id}`}))}]}/></Form.Item><Form.Item name="description" label="说明"><Input.TextArea rows={3}/></Form.Item></Form></Modal>
  <Modal className="merchant-config-modal" width={920} title="注册商户" open={merchantCreateOpen} onOk={createMerchant} okText="保存商户" cancelText="取消" okButtonProps={{size:'large'}} cancelButtonProps={{size:'large'}} onCancel={()=>{setMerchantCreateOpen(false);merchantForm.resetFields()}}><div className="merchant-modal-lead"><SafetyCertificateOutlined/><div><Typography.Text strong>建立商户档案</Typography.Text><Typography.Text type="secondary">填写基本信息，并录入汇付提供的接入资料。字段名称由系统统一管理。</Typography.Text></div></div><Form form={merchantForm} layout="vertical"><Card className="merchant-section-card" title={<div><Typography.Text strong>基本信息</Typography.Text><Typography.Text type="secondary">用于平台内识别和管理商户</Typography.Text></div>}><div className="merchant-identity-grid"><Form.Item name="code" label="商户编码" extra="例如：BRAND_SHANGHAI" rules={[{required:true,message:'请输入商户编码'}]}><Input size="large" placeholder="请输入商户编码"/></Form.Item><Form.Item name="name" label="商户名称" rules={[{required:true,message:'请输入商户名称'}]}><Input size="large" placeholder="请输入便于识别的商户名称"/></Form.Item><Form.Item className="merchant-grid-full" name="description" label="备注"><Input.TextArea rows={2} placeholder="选填，例如门店、用途或负责人"/></Form.Item></div></Card><ConfigurationFields fields={configurationFields}/></Form></Modal>
  <Modal className="merchant-config-modal" width={920} title={`配置 ${configMerchant?.name||''}`} open={!!configMerchant} onOk={saveConfiguration} okText="保存配置" cancelText="取消" okButtonProps={{size:'large'}} cancelButtonProps={{size:'large'}} onCancel={()=>{setConfigMerchant(undefined);configForm.resetFields()}}><div className="merchant-modal-lead"><SafetyCertificateOutlined/><div><Typography.Text strong>汇付接入资料</Typography.Text><Typography.Text type="secondary">只需粘贴对应内容，无需输入或修改技术字段名。</Typography.Text></div></div><Form form={configForm} layout="vertical"><ConfigurationFields fields={configurationFields}/></Form></Modal>
  <Drawer title="任务模板详情" width={760} open={!!selectedTemplate} onClose={()=>setSelectedTemplate(undefined)}>
    {selectedTemplate&&<><Typography.Title level={3} style={{marginTop:0}}>{selectedTemplate.displayName}</Typography.Title><Space wrap style={{marginBottom:16}}><Tag color="blue">{selectedTemplate.category}</Tag><Typography.Text type="secondary">{selectedTemplate.id}</Typography.Text></Space>{selectedTemplate.description&&<Typography.Paragraph type="secondary">{selectedTemplate.description}</Typography.Paragraph>}<Descriptions bordered size="small" column={1} style={{marginBottom:24}}><Descriptions.Item label="模板字段">共 {selectedTemplate.inputFields.length} 项</Descriptions.Item><Descriptions.Item label="必填字段">{selectedTemplate.inputFields.filter(field=>field.required).length} 项</Descriptions.Item><Descriptions.Item label="选填字段">{selectedTemplate.inputFields.filter(field=>!field.required).length} 项</Descriptions.Item></Descriptions><Divider orientation="left">任务参数</Divider><Form layout="vertical" disabled initialValues={{inputs:Object.fromEntries(selectedTemplate.inputFields.filter(field=>field.defaultValue).map(field=>[field.key,field.defaultValue]))}}>{selectedTemplate.inputFields.map(field=>renderField(field,true))}</Form></>}
  </Drawer>
  <Drawer title="流程模板详情" width={760} open={!!selectedWorkflow} onClose={()=>setSelectedWorkflow(undefined)}>
    {selectedWorkflow&&<><Typography.Title level={3} style={{marginTop:0}}>{selectedWorkflow.displayName}</Typography.Title><Space wrap style={{marginBottom:16}}><Tag color="blue">{selectedWorkflow.category}</Tag><Typography.Text type="secondary">{selectedWorkflow.id} · v{selectedWorkflow.version}</Typography.Text></Space><Typography.Paragraph type="secondary">{selectedWorkflow.description}</Typography.Paragraph><Divider orientation="left">执行步骤</Divider>{selectedWorkflow.steps.map(step=><Card size="small" key={step.key} style={{marginBottom:10}}><Flex justify="space-between" wrap><Space><Tag color={step.polling?'orange':step.optional?'default':'blue'}>{step.order+1}</Tag><Typography.Text strong>{step.templateName}</Typography.Text><Typography.Text type="secondary">{step.key}</Typography.Text></Space><Space>{step.optional&&<Tag>可选</Tag>}{step.polling&&<Tag color="orange">每 {step.intervalSeconds} 秒轮询，最多 {step.maxAttempts} 次</Tag>}</Space></Flex></Card>)}<Alert showIcon type="info" message="图片上传步骤仅在填写图片路径或 URL 时执行" description={<span>后续步骤可在 JSON 字段中使用 <Typography.Text code>{'${steps.picture-upload.file_id}'}</Typography.Text> 引用上传结果。</span>}/></>}
  </Drawer>
  <Drawer title="执行日志" width={640} open={logOpen} onClose={()=>setLogOpen(false)}>{logs.map(log=><div className="log-line" key={log.id}><Tag color={log.level==='ERROR'?'error':'blue'}>{log.level}</Tag><Typography.Text>{new Date(log.createdAt).toLocaleString()} · {log.message}</Typography.Text></div>)}</Drawer>
  <Drawer title="执行结果" width={720} open={!!selectedExecution} onClose={()=>setSelectedExecution(undefined)}>{selectedExecution&&<Space direction="vertical" size={16} style={{width:'100%'}}>{selectedExecution.errorMessage&&<Alert type="error" showIcon message={selectedExecution.errorMessage}/>} {findOutputValue(selectedExecution.outputs,'file_id')&&<Alert type="success" showIcon message="图片上传成功" description={<Typography.Text copyable>{findOutputValue(selectedExecution.outputs,'file_id')}</Typography.Text>}/>}<Card size="small" title="任务返回"><pre style={{margin:0,whiteSpace:'pre-wrap',wordBreak:'break-all'}}>{JSON.stringify(selectedExecution.outputs||{},null,2)}</pre></Card>{selectedExecution.steps?.map(step=><Card size="small" key={step.id} title={`${step.stepIndex+1}. ${step.stepKey}`} extra={<Tag color={statusColor[step.status]}>{step.status}</Tag>}><pre style={{margin:0,whiteSpace:'pre-wrap',wordBreak:'break-all'}}>{JSON.stringify(step.outputs||{},null,2)}</pre></Card>)}</Space>}</Drawer>
  </Layout.Content></Layout></ConfigProvider>
}

function ConfigurationFields({fields}:{fields:MerchantConfigurationField[]}){const basics=fields.filter(field=>!field.multiline),keys=fields.filter(field=>field.multiline);const fieldControl=(field:MerchantConfigurationField)=><Form.Item key={field.key} name={['configuration',field.key]} label={<Flex align="center" justify="space-between" gap={8}><Typography.Text strong>{field.label}</Typography.Text><Space size={6}><Tag bordered={false} className="merchant-tech-key">{field.key}</Tag>{!field.required&&<Tag bordered={false}>选填</Tag>}</Space></Flex>} extra={field.description} rules={field.required?[{required:true,whitespace:true,message:`请填写${field.label}`}]:undefined}>{field.secret?<Input.Password size="large" placeholder={field.placeholder} autoComplete="new-password"/>:field.multiline?<Input.TextArea autoSize={{minRows:3,maxRows:6}} placeholder={field.placeholder}/>:<Input size="large" placeholder={field.placeholder}/>}</Form.Item>;return <div className="merchant-config-content"><Card className="merchant-section-card" title={<div><Typography.Text strong>账户标识</Typography.Text><Typography.Text type="secondary">请从汇付提供的接入资料中复制，避免手工改写</Typography.Text></div>}><div className="merchant-basic-grid">{basics.map(fieldControl)}</div></Card><Card className="merchant-section-card merchant-key-section" title={<div><Typography.Text strong>密钥配置</Typography.Text><Typography.Text type="secondary">用于请求签名和返回验签，请粘贴完整内容</Typography.Text></div>}>{keys.map(field=><div className={`merchant-key-card${field.secret?' is-private':''}`} key={field.key}><div className="merchant-key-accent"><LockOutlined/></div><div className="merchant-key-field">{fieldControl(field)}</div></div>)}<div className="merchant-security-note"><LockOutlined/><div><Typography.Text strong>私钥安全提示</Typography.Text><Typography.Text type="secondary">商户私钥仅用于接口签名，请勿通过聊天、邮件或截图发送。</Typography.Text></div></div></Card></div>}
